spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/beer
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
